[project]
name = "crewai-acp-music-agent-server"
version = "0.1.0"
description = "A CrewAI agent server for ACP-based multi-agent songwriting and Markdown reporting."
requires-python = ">=3.11, <4.0"
dependencies = [
    "acp-sdk==1.0.1",
    "crewai[tools]>=0.95.0",
    "agentops==0.4.19"
]

